export { default as CArrow } from "./CArrow/CArrow.vue";
export { default as CButton } from "./CButton/CButton.vue";
export { default as CCheckbox } from "./CCheckbox/CCheckbox.vue";
export { default as CInput } from "./CInput/CInput.vue";
export { default as CMessage } from "./CMessage/CMessage.vue";
export { default as CVideo } from "./CVideo/CVideo.vue";
export { default as CLogo } from "./CLogo/CLogo.vue";
export { default as CVersion } from "./CVersion/CVersion.vue";
export { default as CTextArea } from "./CTextArea/CTextArea.vue";
